### ISSUE TITLE
Support for pinned tabs and auto-saving

### ISSUE THREAD

**Issue by orschiro** [Conchylicultor/TabsFolder#1]
Dear @Conchylicultor,

Thank you very much for this great extension!

I have two questions:
1. Does it support auto-saving? Let's say I add/remove tabs in the group I am working on. Will these changes automatically be saved under the existing tab name?
2. Does it support pinned state of tabs?

Thankfully,

Robert

**Comment by Conchylicultor** [comment]
Thanks for your message.
1. I don't really understand what you're asking. What changes are you talking about. If you add a tab in the working group by drag&drop, the tab is simply opened directly. There is no save button so when you do a modification in the tabs manager page, it's automatically saved.
2. Now it does, but I'm not sure of what behavior is expected so I have launched a survey:
   https://docs.google.com/forms/d/1dZgRd7THA22sk5-a13XfgY8aHJ_T6XYc8JcAU5qqMno/viewform

**Comment by orschiro** [comment]
> There is no save button so when you do a modification in the tabs manager page, it's automatically saved.

That's what I wanted to know. Sorry for my imprecise question. 

> Now it does, but I'm not sure of what behavior is expected so I have launched a survey:

Thanks! Indeed, please feel free to revert this if the majority dislikes this "feature".

**Comment by Conchylicultor** [comment]
Now the pinned tabs stays opened when switching group.
