### ISSUE TITLE
Feature request: Close tab of extension after clicking 'Work with this group'

### ISSUE THREAD

**Issue by heese** [Conchylicultor/TabsFolder#4]
I wished the tab of the extension would automatically close after I clicked the button '_Work with this group_'. At the moment I have to close manually.

**Comment by bruno-robert** [comment]
I was looking to see if someone else thought this was a good feature. Happy to see I'm not alone. I think the developer has stopped working on this project. I was thinking of adding this option myself, but I have no prior experience with chrome extensions.

**Comment by bruno-robert** [comment]
I've posted a pull request with this fix. The one way I see it could be improved is by creating a settings menu that would allow the user to choose between auto-close or manual close.

**Comment by Conchylicultor** [comment]
Thank you for your comments. Solved with e5f968391f2fa280c511fc8bf5fbd95e5bec638f
